[
  {
    athlete: "Alicia Coutts",
    age: 24,
    country: "Australia",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: "1",
    __meta__: {
      country: {
        headId: "1",
        leafIds: ["2", "3", "4", "5", "6", "7"],
      },
      athlete: {
        headId: "1",
        leafids: undefined,
      },
      sport: {
        headId: "1",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Ian Thorpe",
    age: 17,
    country: "Australia",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 3,
    silver: 2,
    bronze: 0,
    total: 5,
    id: "2",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "2",
        leafIds: ["3"],
      },
      sport: {
        headId: "2",
        leafIds: ["3"],
      },
    },
  },
  {
    athlete: "Ian Thorpe",
    age: 21,
    country: "Australia",
    year: 2004,
    date: "29/08/2004",
    sport: "Swimming",
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: "3",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "2",
        leafIds: undefined,
      },
      sport: {
        headId: "2",
        leafIds: undefined,
      },
    },
  },
  {
    athlete: "Libby Lenton-Trickett",
    age: 23,
    country: "Australia",
    year: 2008,
    date: "24/08/2008",
    sport: "Swimming",
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: "4",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "4",
        leafids: undefined,
      },
      sport: {
        headId: "4",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Michael Klim",
    age: 23,
    country: "Australia",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 2,
    silver: 2,
    bronze: 0,
    total: 4,
    id: "5",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "5",
        leafids: undefined,
      },
      sport: {
        headId: "5",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Petria Thomas",
    age: 28,
    country: "Australia",
    year: 2004,
    date: "29/08/2004",
    sport: "Swimming",
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: "6",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "6",
        leafids: undefined,
      },
      sport: {
        headId: "6",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Susie O'Neill",
    age: 27,
    country: "Australia",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: "7",
    __meta__: {
      country: {
        headId: "1",
        leafIds: undefined,
      },
      athlete: {
        headId: "7",
        leafids: undefined,
      },
      sport: {
        headId: "7",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Cindy Klassen",
    age: 26,
    country: "Canada",
    year: 2006,
    date: "26/02/2006",
    sport: "Speed Skating",
    gold: 1,
    silver: 2,
    bronze: 2,
    total: 5,
    id: "8",
    __meta__: {
      country: {
        headId: "8",
        leafIds: undefined,
      },
      athlete: {
        headId: "8",
        leafids: undefined,
      },
      sport: {
        headId: "8",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Sun Yang",
    age: 20,
    country: "China",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: "9",
    __meta__: {
      country: {
        headId: "9",
        leafIds: undefined,
      },
      athlete: {
        headId: "9",
        leafids: undefined,
      },
      sport: {
        headId: "9",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Inge de Bruijn",
    age: 27,
    country: "Netherlands",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 3,
    silver: 1,
    bronze: 0,
    total: 4,
    id: "10",
    __meta__: {
      country: {
        headId: "10",
        leafIds: ["11", "12"],
      },
      athlete: {
        headId: "10",
        leafIds: ["11"],
      },
      sport: {
        headId: "10",
        leafIds: ["11"],
      },
    },
  },
  {
    athlete: "Inge de Bruijn",
    age: 30,
    country: "Netherlands",
    year: 2004,
    date: "29/08/2004",
    sport: "Swimming",
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: "11",
    __meta__: {
      country: {
        headId: "10",
        leafIds: undefined,
      },
      athlete: {
        headId: "10",
        leafIds: undefined,
      },
      sport: {
        headId: "10",
        leafIds: undefined,
      },
    },
  },
  {
    athlete: "Pieter van den Hoogenband",
    age: 22,
    country: "Netherlands",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: "12",
    __meta__: {
      country: {
        headId: "10",
        leafIds: undefined,
      },
      athlete: {
        headId: "12",
        leafIds: undefined,
      },
      sport: {
        headId: "12",
        leafIds: undefined,
      },
    },
  },
  {
    athlete: "Marit Bjørgen",
    age: 29,
    country: "Norway",
    year: 2010,
    date: "28/02/2010",
    sport: "Cross Country Skiing",
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: "13",
    __meta__: {
      country: {
        headId: "13",
        leafids: undefined,
      },
      athlete: {
        headId: "13",
        leafids: undefined,
      },
      sport: {
        headId: "13",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Aleksey Nemov",
    age: 24,
    country: "Russia",
    year: 2000,
    date: "01/10/2000",
    sport: "Gymnastics",
    gold: 2,
    silver: 1,
    bronze: 3,
    total: 6,
    id: "14",
    __meta__: {
      country: {
        headId: "14",
        leafIds: ["15"],
      },
      athlete: {
        headId: "14",
        leafids: undefined,
      },
      sport: {
        headId: "14",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Aliya Mustafina",
    age: 17,
    country: "Russia",
    year: 2012,
    date: "12/08/2012",
    sport: "Gymnastics",
    gold: 1,
    silver: 1,
    bronze: 2,
    total: 4,
    id: "15",
    __meta__: {
      country: {
        headId: "14",
        leafIds: undefined,
      },
      athlete: {
        headId: "15",
        leafids: undefined,
      },
      sport: {
        headId: "15",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "An Hyeon-Su",
    age: 20,
    country: "South Korea",
    year: 2006,
    date: "26/02/2006",
    sport: "Short-Track Speed Skating",
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: "16",
    __meta__: {
      country: {
        headId: "16",
        leafids: undefined,
      },
      athlete: {
        headId: "16",
        leafids: undefined,
      },
      sport: {
        headId: "16",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Allison Schmitt",
    age: 22,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 3,
    silver: 1,
    bronze: 1,
    total: 5,
    id: "17",
    __meta__: {
      country: {
        headId: "17",
        leafIds: ["18", "19", "...20 ~ 27...", "28", "29"],
      },
      athlete: {
        headId: "17",
        leafids: undefined,
      },
      sport: {
        headId: "17",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Dara Torres",
    age: 33,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 2,
    silver: 0,
    bronze: 3,
    total: 5,
    id: "18",
    __meta__: {
      country: {
        headId: "17",
        leafIds: undefined,
      },
      athlete: {
        headId: "18",
        leafids: undefined,
      },
      sport: {
        headId: "18",
        leafids: undefined,
      },
    },
  },
  {
    athlete: "Gary Hall Jr.",
    age: 25,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 2,
    silver: 1,
    bronze: 1,
    total: 4,
    id: "19",
    __meta__: {
      comment:
        "need more? I think above examples are sufficient to understant meta field",
    },
  },
  {
    athlete: "Jenny Thompson",
    age: 27,
    country: "United States",
    year: 2000,
    date: "01/10/2000",
    sport: "Swimming",
    gold: 3,
    silver: 0,
    bronze: 1,
    total: 4,
    id: "20",
    __meta__: {},
  },
  {
    athlete: "Michael Phelps",
    age: 19,
    country: "United States",
    year: 2004,
    date: "29/08/2004",
    sport: "Swimming",
    gold: 6,
    silver: 0,
    bronze: 2,
    total: 8,
    id: "21",
    __meta__: {},
  },
  {
    athlete: "Michael Phelps",
    age: 23,
    country: "United States",
    year: 2008,
    date: "24/08/2008",
    sport: "Swimming",
    gold: 8,
    silver: 0,
    bronze: 0,
    total: 8,
    id: "22",
    __meta__: {},
  },
  {
    athlete: "Michael Phelps",
    age: 27,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 4,
    silver: 2,
    bronze: 0,
    total: 6,
    id: "23",
    __meta__: {},
  },
  {
    athlete: "Missy Franklin",
    age: 17,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 4,
    silver: 0,
    bronze: 1,
    total: 5,
    id: "24",
    __meta__: {},
  },
  {
    athlete: "Nastia Liukin",
    age: 18,
    country: "United States",
    year: 2008,
    date: "24/08/2008",
    sport: "Gymnastics",
    gold: 1,
    silver: 3,
    bronze: 1,
    total: 5,
    id: "25",
    __meta__: {},
  },
  {
    athlete: "Natalie Coughlin",
    age: 21,
    country: "United States",
    year: 2004,
    date: "29/08/2004",
    sport: "Swimming",
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: "26",
    __meta__: {},
  },
  {
    athlete: "Natalie Coughlin",
    age: 25,
    country: "United States",
    year: 2008,
    date: "24/08/2008",
    sport: "Swimming",
    gold: 1,
    silver: 2,
    bronze: 3,
    total: 6,
    id: "27",
    __meta__: {},
  },
  {
    athlete: "Ryan Lochte",
    age: 24,
    country: "United States",
    year: 2008,
    date: "24/08/2008",
    sport: "Swimming",
    gold: 2,
    silver: 0,
    bronze: 2,
    total: 4,
    id: "28",
    __meta__: {},
  },
  {
    athlete: "Ryan Lochte",
    age: 27,
    country: "United States",
    year: 2012,
    date: "12/08/2012",
    sport: "Swimming",
    gold: 2,
    silver: 2,
    bronze: 1,
    total: 5,
    id: "29",
    __meta__: {},
  },
  {
    athlete: "Kirsty Coventry",
    age: 24,
    country: "Zimbabwe",
    year: 2008,
    date: "24/08/2008",
    sport: "Swimming",
    gold: 1,
    silver: 3,
    bronze: 0,
    total: 4,
    id: "30",
    __meta__: {},
  },
];
